# Generated by Django 5.1.2 on 2025-12-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(help_text='User-declared country of residence', max_length=64)),
                ('issuing_country', models.CharField(help_text='Country that issued the document', max_length=64)),
                ('document_type', models.CharField(choices=[('passport', 'Passport'), ('driver_license', "Driver's licence"), ('national_id', 'National ID'), ('residence_permit', 'Residence permit')], default='passport', max_length=32)),
                ('document_number', models.CharField(max_length=32)),
                ('date_of_birth', models.DateField()),
                ('doc_expiry', models.DateField()),
                ('ip_country', models.CharField(blank=True, max_length=64)),
                ('device_os', models.CharField(default='web', max_length=32)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('attempt_count', models.PositiveIntegerField(default=1)),
                ('onboarding_channel', models.CharField(choices=[('web', 'Web SDK'), ('ios', 'iOS SDK'), ('android', 'Android SDK')], default='web', max_length=24)),
                ('selfie_quality', models.PositiveIntegerField(default=70)),
                ('doc_authenticity_score', models.PositiveIntegerField(default=0)),
                ('face_match_score', models.PositiveIntegerField(default=0)),
                ('liveness_passed', models.BooleanField(default=False)),
                ('fraud_risk_score', models.PositiveIntegerField(default=0)),
                ('fraud_signals', models.JSONField(blank=True, default=dict)),
                ('aml_findings', models.JSONField(blank=True, default=dict)),
                ('age_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('needs_review', 'Needs review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=24)),
                ('risk_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
