# Generated by Django 5.1.2 on 2026-01-25 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_verificationcase_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('review', 'Manual review'), ('rerun', 'Re-run'), ('note', 'Note')], max_length=24)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='verification.verificationcase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
